version: '3.8'
services:
  
  dotnet_main:
    image: dotnet-web
    ports:
      - 5001:80
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    environment:
      ConnectionStrings__Default: "Host=dotnet_postgres;Username=admin;Password=12345;Database=PostgresDb"
    depends_on:
      - dotnet_postgres
  
  dotnet_postgres:
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: PostgresDb
          
#
#  dotnet_rabbitmq:
#    image: rabbitmq:3-alpine
#
#  dotnet_minio:
#    image: minio/minio:latest
#
#  dotnet_mongodb:
#    image: mongo:latest
#
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
#
#  dotnet_mailing:
#    image: dotnet-web
#
#  dotnet_storage:
#    image: dotnet-web